version: "3.9"
services:
  api:
    build: .
    restart: always
    ports:
      - "9000:9000"
    env_file: .env
    depends_on:
      database:
        condition: service_started
    networks:
      - meffin-transactions-network

  database:
    image: postgres:latest
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - meffin-transactions-network

volumes:
  db:

networks:
  meffin-transactions-network: